title:        API Definitions
url:          http://definitions.apievangelist.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 150
paginate_path: "/news/page:num"

production_url : http://definitions.apievangelist.com

BASE_PATH : http://definitions.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html

# Masthead title
masthead_link: http://apis.how/xzca4kr2wb
masthead_font_size: 20
masthead_title: '{"API Definitions"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45

# Project

project_image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
project_summary: Keeping an eye on API definitions, from formats like API Blueprint, OADF, and RAML, to APIs.json.

# Navigation
navigation:
  - label1: Home
    link1: /index.html
    label2:
    link2:
  - label1: News
    link1: /news/
    label2: RSS
    link2: /blog.xml
  - label1: Organizations
    link1: /companies.html
    label2: JSON
    link2: /data/companies.json
  - label1: Building Blocks
    link1: /building-blocks.html
    label2: JSON
    link2: /data/buildingblocks.json
  - label1: Tools
    link1: /tools.html
    label2: JSON
    link2: /data/tools.json
  - label1: (View as PDF Guide)
    link1: http://bit.ly/1ISZ1I9
    label2:
    link2:
  - label1: << Return to API Evangelist
    link1: http://apievangelist.com
    label2:
    link2:

# sponsors
sponsors_padding_top: 10
